#+TITLE: syzMetab
#+AUTHOR: ZGUANG@LZU
#+DATE:
#+OPTIONS: H:4 toc:nil ^:{} num:t html-style:nil html-scripts:nil
#+STARTUP: content

syzMetab: R package for metabolic network construction, visualization and analysis with igraph.

* Warning
- The package is still under active development. All components may be changed in future versions.

* Installation
- NOTE: install latest (dev) version of igraph, or you may encounter some problems:
#+begin_src R :exports code :tangle yes :eval never :ravel eval=FALSE
  require('devtools')
  install_github("igraph/rigraph@master")
  install_github('zgzhao/syzMetab')
#+end_src

* Terms
Followings are terms used in "syzMetab" package.
** metabolic pathway
A metabolic pathway refer to meta data parsed from a KEGG xml (KGML) file and is represented by KDataSet S4 class.

Data slots in "KDataSet" object:
- pathInfo: list
- entries: EntryList
- reactions: ReactionList
- relations: RelationList
- graphics: GraphicList

** metabolic graph
It is an igraph object with "mgraph" class attribute and additional attributes holding reactions associated data.

Most network algorithms for igraph can apply to mgraph directly; however, since metabolic networks have their uniqe natures, some algorithms should be adjusted accordingly.

** reaction
Reactions play key roles in metabolic network construction and downstream analysis.
Two classes are designed in syzMetab package for reactions handling: "ReactionList" and "ReactionSet".
The former is virtual class of "list" and the latter is a S4 class.

Generally, a reaction should contain minimun data of:
- substrate(s)
- product(s)
- gene(s)/enzyme(s)
- identifier
After translated into graph components, relations among substrates or products will lose. Therefore, reaction identifiers (or other mechanisms) are required to keep these traces.
